### ISSUE TITLE
how do i set the subject?

### ISSUE THREAD

**Issue by marexx** [Mirko-Solutions/typo3-newsletter#13]
Setting: TYPO3 [11.5.25]
Newsletter: 5.0.3

Everything works fine, except the newsletter has no subject, how do i set it?

MArek

**Comment by konorws** [comment]
@marexx Hello, can you provide specific steps to reproduce the error, and also show your email that you received without a "subject"

**Comment by Runik51ua** [comment]
Hi @marexx, Currently, the subject is automatically generated from the page title (value inside title tag), we will add possibility to manually change it in near future

**Comment by marexx** [comment]
I think it was my fault,
