### ISSUE TITLE
`EmailController::notifyUnsubscribe()` uses old message API

### ISSUE THREAD

**Issue by cundd** [Mirko-Solutions/typo3-newsletter#8]
It looks like `\Mirko\Newsletter\Controller\EmailController::notifyUnsubscribe()` is using old (non-Symfony) API calls to send the notification.

The main issue is line [335](https://github.com/iresults/newsletter/blob/32d2da53b707e609388238c4b3a5861ac1673d24/Classes/Controller/EmailController.php#L335).

**Comment by Runik51ua** [comment]
[completed] in https://github.com/Mirko-Solutions/newsletter/pull/6
